import os
import shutil
import subprocess
from multiprocessing import Pool

WINDOWS =  os.name == "nt"

def get_dotbin_home():
    return os.path.dirname(os.path.dirname(__file__))

def find_scripts(dotbin_home):
    scripts = []
    for script in os.listdir(dotbin_home):
        if script.endswith(".py"):
            scripts.append(os.path.join(dotbin_home, script))
    return scripts

def create_script_shim(dotbin_bin, script_path, get_script):
    name = os.path.basename(script_path)
    name, _ = os.path.splitext(name)
    if WINDOWS:
        name = name + ".cmd"
    shim_path = os.path.join(dotbin_bin, name)
    print(f"creating: {shim_path}")
    with open(shim_path, "w", encoding="utf-8") as f:
        executable = os.path.abspath(script_path)
        if WINDOWS:
            f.write("@echo off\r\n")
        else:
            f.write("#!/usr/bin/bash\n")
        f.write(get_script(executable))
    if not WINDOWS:
        subprocess.run(["chmod", "+x", shim_path], check=True)

def ps_probe_command(command):
    result = subprocess.run(["pwsh", "-NoLogo", "-NoProfile", "-Command", "& { Test-Path Alias:"+command+" }"], capture_output=True)
    if result.returncode == 0 and result.stdout.decode().strip() != "False":
        return "alias", command
    result = subprocess.run(["pwsh", "-NoLogo", "-NoProfile", "-Command", "& { Get-Command "+command+" }"], capture_output=True)
    if result.returncode == 0:
        return "command", command
    return None, command

def setup_coreutils(dotbin_home, dotbin_bin):
    if not WINDOWS:
        return
    
    # extra utils
    dotbin_windows = os.path.join(dotbin_home, "windows")
    subprocess.run(["cargo", "build", "--bin", "which", "--release"], check=True, cwd=dotbin_windows)
    shutil.copy(os.path.join(dotbin_windows, "target", "release", "which.exe"), dotbin_bin)

    # extra scripts
    for script in os.listdir(dotbin_windows):
        if not script.endswith(".ps1"):
            continue
        print(script)
        target=os.path.join(dotbin_bin, script)
        shutil.copyfile(os.path.join(dotbin_windows, script), target)

    # uutils/coreutils
    try:
        result = subprocess.run(["coreutils", "--list"], check=True, capture_output=True)
    except:
        subprocess.run(["cargo", "install", "coreutils"], check=True)
        result = subprocess.run(["coreutils", "--list"], check=True, capture_output=True)
    util_names = list(set(line.strip() for line in result.stdout.decode().splitlines() if line.strip() != "["))
    for util in util_names:
        if util == "ls":
            ok, _ = ps_probe_command("eza")
            if ok is not None:
                # use eza for ls
                create_script_shim(dotbin_bin, util, lambda _: "eza %*")
                continue
        create_script_shim(dotbin_bin, util, lambda x: f"coreutils {os.path.basename(x)} %*")
    ps_profile_dir = os.path.dirname(subprocess.run(["pwsh", "-NoLogo", "-NoProfile", "-Command", "& { echo $PROFILE.CurrentUserCurrentHost }"], check=True, capture_output=True).stdout.decode().strip())
    os.makedirs(ps_profile_dir, exist_ok=True)

    to_add = set()
    with Pool() as p:
        for add, util in p.imap_unordered(ps_probe_command, util_names):
            if add is not None:
                to_add.add((add, util))
    # Additional utilities alias
    to_add.add(("alias", "curl")) # Remove curl -> Invoke-WebRequest if exists (Might exist for powershell 5 but not pwsh)
    with open(os.path.join(ps_profile_dir, "Initialize-Coreutils.ps1"), "w") as f:
        f.write("# This file is generated by Pistonight/dotbin\n")
        for typ, util in sorted(to_add):
            if typ == "alias":
                f.write(f"if (Test-Path Alias:{util}) {{ Remove-Item Alias:{util} -Force }}\n")
            else:
                f.write(f"Set-Alias -Name {util} -Value \"{os.path.join(dotbin_bin, util)}.cmd\" \n")
    
    print(f"Add the following to your PowerShell profile to enable the coreutils")
    print()
    print("# Coreutils")
    print(". $PSScriptRoot\\Initialize-Coreutils.ps1")

def setup_archlinux_utils(dotbin_home, dotbin_bin):
    if WINDOWS:
        return
    dotbin_archlinux = os.path.join(dotbin_home, "archlinux")
    for script in os.listdir(dotbin_archlinux):
        print(script)
        target=os.path.join(dotbin_bin, script)
        shutil.copyfile(os.path.join(dotbin_archlinux, script), target)
        subprocess.run(["chmod", "+x", target], check=True)

if __name__ == "__main__":
    dotbin_home = get_dotbin_home()
    dotbin_bin = os.path.join(dotbin_home, "bin")
    if os.path.exists(dotbin_bin):
        shutil.rmtree(dotbin_bin)
    os.makedirs(dotbin_bin)
    scripts = find_scripts(dotbin_home)
    for script in scripts:
        create_script_shim(dotbin_bin, script ,
            lambda executable:
                f"python \"{executable}\" %*" if WINDOWS else "exec \"{executable}\" \"$@\""
                           )
    setup_coreutils(dotbin_home, dotbin_bin)
    setup_archlinux_utils(dotbin_home, dotbin_bin)
    extra_dir = os.path.join(dotbin_home, "extra")
    bin_dir = os.path.join(extra_dir, "bin")
    portable_dir = os.path.join(extra_dir, "portable")
    symlink_dir = os.path.join(extra_dir, "symlink")
    os.makedirs(bin_dir, exist_ok=True)
    os.makedirs(portable_dir, exist_ok=True)
    os.makedirs(symlink_dir, exist_ok=True)
